name: flutter_app
description: A new Flutter application.

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  english_words: ^4.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  dio: ^4.0.6
  flutter_swiper: ^1.1.6
  url_launcher: ^6.1.2
  flutter_screenutil: ^5.5.3+2
  scoped_model: ^1.1.0
  groovin_material_icons: ^1.1.5
  fluttertoast: ^8.0.9
  rxdart: ^0.27.4
  http: ^0.13.4
  nima: ^1.0.0
  path_drawing: ^1.0.0
  video_player: ^2.4.2
  chewie: ^1.3.3
  webview_flutter: ^3.0.4
  sqflite: ^2.0.2+1
  shared_preferences: ^2.0.15
  path_provider: ^2.0.2
  mapbox_search: ^3.0.1+2
  flutter_picker: ^2.0.3
  share: ^2.0.4
  social_share_plugin: ^0.3.1
  appcheck: ^1.0.3
  address_picker: ^0.0.1
  image_gallery_saver: ^1.6.7
  permission_handler: ^9.2.0
  flutter_share_me:
    git: https://github.com/OpenFlutter/flutter_share_me


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - images/

    - lib/locale/i18n_en.json
    - lib/locale/i18n_zh.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
